### ISSUE TITLE
org.reflections.ReflectionsException: could not create class

### ISSUE THREAD

**Issue by 0k00l** [ingwarsw/arquillian-suite-extension#72]
Cannot use in **Netbeans** @ArquillianSuiteDeployment because of followed issue
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running pl.nbp.test.ApplicationBeanTests
14:43:40,887 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [../common/src/test/resources/logback-test.xml] at [file:/home/dev/Workspace/MIC/sources/mic-backend/ejb/../common/src/test/resources/logback-test.xml]
14:43:40,979 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:43:40,982 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:43:40,987 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:43:41,010 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
14:43:41,010 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:43:41,010 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:43:41,011 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3901d134 - Registering current configuration as safe fallback point
2021-11-22 14:43:41,039 DEBUG [main] org.reflections.Reflections.scan:184 - going to scan these urls:
file:/home/dev/Workspace/MIC/sources/mic-backend/ejb/target/test-classes/
**2021-11-22 14:43:41,051 DEBUG [main] org.reflections.Reflections.scan:257 - could not scan file .netbeans_automatic_build in url file:/home/dev/Workspace/MIC/sources/mic-backend/ejb/target/test-classes/ with scanner TypeAnnotationsScanner
org.reflections.ReflectionsException: could not create class object from file .netbeans_automatic_build**
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
	at org.reflections.Reflections.scan(Reflections.java:253)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.eu.ingwar.tools.arquillian.extension.suite.ArquillianSuiteExtension.getDeploymentClass(ArquillianSuiteExtension.java:82)
	at org.eu.ingwar.tools.arquillian.extension.suite.ArquillianSuiteExtension.register(ArquillianSuiteExtension.java:65)
	at org.jboss.arquillian.core.impl.loadable.LoadableExtensionLoader.load(LoadableExtensionLoader.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.core.impl.ManagerImpl.fireProcessing(ManagerImpl.java:295)
	at org.jboss.arquillian.core.impl.ManagerImpl.<init>(ManagerImpl.java:92)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:144)
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:89)
	at org.jboss.arquillian.core.spi.ManagerBuilder.create(ManagerBuilder.java:68)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.<init>(EventTestRunnerAdaptor.java:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:144)
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:89)
	at org.jboss.arquillian.test.spi.TestRunnerAdaptorBuilder.build(TestRunnerAdaptorBuilder.java:49)
	at org.jboss.arquillian.junit.AdaptorManager.initializeAdaptor(AdaptorManager.java:21)
	at org.jboss.arquillian.junit.AdaptorManagerWithNotifier.initializeAdaptor(AdaptorManagerWithNotifier.java:19)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:109)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.reflections.ReflectionsException: could not create class file from .netbeans_automatic_build
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	... 44 common frames omitted
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at javassist.bytecode.ClassFile.read(ClassFile.java:823)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:154)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
	... 46 common frames omitted
```

I've tired to set property in arquillian.xml <property name="fullClasspathScan">false</property> but it didn't helped (i don't know if i understand this property properly)

**Comment by 0k00l** [comment]
BTW. same issue occurs in shell (of course code has been written in neatbenas)
